//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Accounts_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Accounts_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Accounts_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string Accounts_Shared_TransactionsFilterUserControl_Months {
            get {
                return ResourceManager.GetString("Accounts_Shared_TransactionsFilterUserControl_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethods.
        /// </summary>
        internal static string Accounts_Shared_TransactionsFilterUserControl_PaymentMethods {
            get {
                return ResourceManager.GetString("Accounts_Shared_TransactionsFilterUserControl_PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Accounts_Shared_TransactionsFilterUserControl_Select {
            get {
                return ResourceManager.GetString("Accounts_Shared_TransactionsFilterUserControl_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Accounts_Shared_TransactionsFilterUserControl_Years {
            get {
                return ResourceManager.GetString("Accounts_Shared_TransactionsFilterUserControl_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Accounts_View_Index_Balance {
            get {
                return ResourceManager.GetString("Accounts_View_Index_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientName.
        /// </summary>
        internal static string Accounts_View_Index_ClientName {
            get {
                return ResourceManager.GetString("Accounts_View_Index_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Accounts_View_Index_Comment {
            get {
                return ResourceManager.GetString("Accounts_View_Index_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Accounts_View_Index_CreateNew {
            get {
                return ResourceManager.GetString("Accounts_View_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Accounts_View_Index_Date {
            get {
                return ResourceManager.GetString("Accounts_View_Index_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments Methods.
        /// </summary>
        internal static string Accounts_View_Index_PaymentsMethods {
            get {
                return ResourceManager.GetString("Accounts_View_Index_PaymentsMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string Accounts_View_Index_Sum {
            get {
                return ResourceManager.GetString("Accounts_View_Index_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionName.
        /// </summary>
        internal static string Accounts_View_Index_TransactionName {
            get {
                return ResourceManager.GetString("Accounts_View_Index_TransactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string Accounts_View_Index_UserName {
            get {
                return ResourceManager.GetString("Accounts_View_Index_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Accounts_View_PaymentsMethods_Create_BackToList {
            get {
                return ResourceManager.GetString("Accounts_View_PaymentsMethods_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Accounts_View_PaymentsMethods_Create_Comment {
            get {
                return ResourceManager.GetString("Accounts_View_PaymentsMethods_Create_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Accounts_View_PaymentsMethods_Create_Create {
            get {
                return ResourceManager.GetString("Accounts_View_PaymentsMethods_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create payment method.
        /// </summary>
        internal static string Accounts_View_PaymentsMethods_Create_CreatePaymentMethod {
            get {
                return ResourceManager.GetString("Accounts_View_PaymentsMethods_Create_CreatePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Accounts_View_PaymentsMethods_Create_Name {
            get {
                return ResourceManager.GetString("Accounts_View_PaymentsMethods_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string Accounts_View_PaymentsMethods_Create_Visible {
            get {
                return ResourceManager.GetString("Accounts_View_PaymentsMethods_Create_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit payment method.
        /// </summary>
        internal static string Accounts_View_PaymentsMethods_Edit_EditPaymentMethod {
            get {
                return ResourceManager.GetString("Accounts_View_PaymentsMethods_Edit_EditPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Accounts_View_PaymentsMethods_Edit_Save {
            get {
                return ResourceManager.GetString("Accounts_View_PaymentsMethods_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Accounts_View_PaymentsMethods_Index_CreateNew {
            get {
                return ResourceManager.GetString("Accounts_View_PaymentsMethods_Index_CreateNew", resourceCulture);
            }
        }
    }
}
