//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Addresses_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Addresses_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Addresses_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Addresses_Street_Create_BackToList {
            get {
                return ResourceManager.GetString("Addresses_Street_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Addresses_Street_Create_Create {
            get {
                return ResourceManager.GetString("Addresses_Street_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create street.
        /// </summary>
        internal static string Addresses_Street_Create_CreateStreet {
            get {
                return ResourceManager.GetString("Addresses_Street_Create_CreateStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Addresses_Street_Create_Name {
            get {
                return ResourceManager.GetString("Addresses_Street_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Addresses_Street_Create_Tag {
            get {
                return ResourceManager.GetString("Addresses_Street_Create_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Street.
        /// </summary>
        internal static string Addresses_Street_Edit_EditStreet {
            get {
                return ResourceManager.GetString("Addresses_Street_Edit_EditStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Addresses_Street_Edit_Save {
            get {
                return ResourceManager.GetString("Addresses_Street_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Addresses_Street_Index_CreateNew {
            get {
                return ResourceManager.GetString("Addresses_Street_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Addresses_Street_Index_Edit {
            get {
                return ResourceManager.GetString("Addresses_Street_Index_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Addresses_Street_Index_Name {
            get {
                return ResourceManager.GetString("Addresses_Street_Index_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Addresses_Street_Index_Tag {
            get {
                return ResourceManager.GetString("Addresses_Street_Index_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string Addresses_View_Create_AddNew {
            get {
                return ResourceManager.GetString("Addresses_View_Create_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Addresses_View_Create_BackToList {
            get {
                return ResourceManager.GetString("Addresses_View_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building:.
        /// </summary>
        internal static string Addresses_View_Create_Building {
            get {
                return ResourceManager.GetString("Addresses_View_Create_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string Addresses_View_Create_City {
            get {
                return ResourceManager.GetString("Addresses_View_Create_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Addresses_View_Create_Create {
            get {
                return ResourceManager.GetString("Addresses_View_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create address.
        /// </summary>
        internal static string Addresses_View_Create_CreateAddress {
            get {
                return ResourceManager.GetString("Addresses_View_Create_CreateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details:.
        /// </summary>
        internal static string Addresses_View_Create_Details {
            get {
                return ResourceManager.GetString("Addresses_View_Create_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room:.
        /// </summary>
        internal static string Addresses_View_Create_Room {
            get {
                return ResourceManager.GetString("Addresses_View_Create_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        internal static string Addresses_View_Create_Street {
            get {
                return ResourceManager.GetString("Addresses_View_Create_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string Addresses_View_Create_ValidationSummary {
            get {
                return ResourceManager.GetString("Addresses_View_Create_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string Addresses_View_Edit_AddNew {
            get {
                return ResourceManager.GetString("Addresses_View_Edit_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Addresses_View_Edit_BackToList {
            get {
                return ResourceManager.GetString("Addresses_View_Edit_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string Addresses_View_Edit_Building {
            get {
                return ResourceManager.GetString("Addresses_View_Edit_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Addresses_View_Edit_City {
            get {
                return ResourceManager.GetString("Addresses_View_Edit_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Addresses_View_Edit_Details {
            get {
                return ResourceManager.GetString("Addresses_View_Edit_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit address.
        /// </summary>
        internal static string Addresses_View_Edit_EditAddress {
            get {
                return ResourceManager.GetString("Addresses_View_Edit_EditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Addresses_View_Edit_Room {
            get {
                return ResourceManager.GetString("Addresses_View_Edit_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Addresses_View_Edit_Save {
            get {
                return ResourceManager.GetString("Addresses_View_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        internal static string Addresses_View_Edit_Street {
            get {
                return ResourceManager.GetString("Addresses_View_Edit_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string Addresses_View_Index_Building {
            get {
                return ResourceManager.GetString("Addresses_View_Index_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Addresses_View_Index_City {
            get {
                return ResourceManager.GetString("Addresses_View_Index_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Addresses_View_Index_CreateNew {
            get {
                return ResourceManager.GetString("Addresses_View_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Street.
        /// </summary>
        internal static string Addresses_View_Index_CreateNewStreet {
            get {
                return ResourceManager.GetString("Addresses_View_Index_CreateNewStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Addresses_View_Index_Details {
            get {
                return ResourceManager.GetString("Addresses_View_Index_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Addresses_View_Index_Edit {
            get {
                return ResourceManager.GetString("Addresses_View_Index_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Addresses_View_Index_Room {
            get {
                return ResourceManager.GetString("Addresses_View_Index_Room", resourceCulture);
            }
        }
    }
}
