//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hosts_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hosts_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Hosts_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string Hosts_View_Create_Address {
            get {
                return ResourceManager.GetString("Hosts_View_Create_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Hosts_View_Create_BackToList {
            get {
                return ResourceManager.GetString("Hosts_View_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Hosts_View_Create_Create {
            get {
                return ResourceManager.GetString("Hosts_View_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Host.
        /// </summary>
        internal static string Hosts_View_Create_CreateNewHost {
            get {
                return ResourceManager.GetString("Hosts_View_Create_CreateNewHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        internal static string Hosts_View_Create_UserName {
            get {
                return ResourceManager.GetString("Hosts_View_Create_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPassword:.
        /// </summary>
        internal static string Hosts_View_Create_UserPassword {
            get {
                return ResourceManager.GetString("Hosts_View_Create_UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string Hosts_View_Create_ValidationSummary {
            get {
                return ResourceManager.GetString("Hosts_View_Create_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string Hosts_View_Edit_Address {
            get {
                return ResourceManager.GetString("Hosts_View_Edit_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Hosts_View_Edit_BackToList {
            get {
                return ResourceManager.GetString("Hosts_View_Edit_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Host:.
        /// </summary>
        internal static string Hosts_View_Edit_EditHost {
            get {
                return ResourceManager.GetString("Hosts_View_Edit_EditHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Hosts_View_Edit_Save {
            get {
                return ResourceManager.GetString("Hosts_View_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        internal static string Hosts_View_Edit_UserName {
            get {
                return ResourceManager.GetString("Hosts_View_Edit_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPassword:.
        /// </summary>
        internal static string Hosts_View_Edit_UserPassword {
            get {
                return ResourceManager.GetString("Hosts_View_Edit_UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string Hosts_View_Edit_ValidationSummary {
            get {
                return ResourceManager.GetString("Hosts_View_Edit_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Hosts_View_Index_Address {
            get {
                return ResourceManager.GetString("Hosts_View_Index_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Hosts_View_Index_Create {
            get {
                return ResourceManager.GetString("Hosts_View_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Hosts_View_Index_Delete {
            get {
                return ResourceManager.GetString("Hosts_View_Index_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastUpdatedDate.
        /// </summary>
        internal static string Hosts_View_Index_LastUpdatedDate {
            get {
                return ResourceManager.GetString("Hosts_View_Index_LastUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Hosts_View_Index_Select {
            get {
                return ResourceManager.GetString("Hosts_View_Index_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string Hosts_View_Index_Selected {
            get {
                return ResourceManager.GetString("Hosts_View_Index_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string Hosts_View_Index_UserName {
            get {
                return ResourceManager.GetString("Hosts_View_Index_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPassword.
        /// </summary>
        internal static string Hosts_View_Index_UserPassword {
            get {
                return ResourceManager.GetString("Hosts_View_Index_UserPassword", resourceCulture);
            }
        }
    }
}
