//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Messages_View_Create_BackToList {
            get {
                return ResourceManager.GetString("Messages_View_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Messages_View_Create_Create {
            get {
                return ResourceManager.GetString("Messages_View_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new message.
        /// </summary>
        internal static string Messages_View_Create_CreateNewMessage {
            get {
                return ResourceManager.GetString("Messages_View_Create_CreateNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageType.
        /// </summary>
        internal static string Messages_View_Create_MessageTypeId {
            get {
                return ResourceManager.GetString("Messages_View_Create_MessageTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Messages_View_Create_Text {
            get {
                return ResourceManager.GetString("Messages_View_Create_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Messages_View_Create_Title {
            get {
                return ResourceManager.GetString("Messages_View_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Messages_View_Delete_BackToList {
            get {
                return ResourceManager.GetString("Messages_View_Delete_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Messages_View_Delete_Date {
            get {
                return ResourceManager.GetString("Messages_View_Delete_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Messages_View_Delete_Delete {
            get {
                return ResourceManager.GetString("Messages_View_Delete_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Message ?.
        /// </summary>
        internal static string Messages_View_Delete_DeleteThisMessage {
            get {
                return ResourceManager.GetString("Messages_View_Delete_DeleteThisMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string Messages_View_Delete_From {
            get {
                return ResourceManager.GetString("Messages_View_Delete_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageType:.
        /// </summary>
        internal static string Messages_View_Delete_MessageType {
            get {
                return ResourceManager.GetString("Messages_View_Delete_MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusId:.
        /// </summary>
        internal static string Messages_View_Delete_StatusId {
            get {
                return ResourceManager.GetString("Messages_View_Delete_StatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        internal static string Messages_View_Delete_Text {
            get {
                return ResourceManager.GetString("Messages_View_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Messages_View_Delete_Title {
            get {
                return ResourceManager.GetString("Messages_View_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string Messages_View_Delete_To {
            get {
                return ResourceManager.GetString("Messages_View_Delete_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Messages_View_Details_BackToList {
            get {
                return ResourceManager.GetString("Messages_View_Details_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Messages_View_Details_Date {
            get {
                return ResourceManager.GetString("Messages_View_Details_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string Messages_View_Details_From {
            get {
                return ResourceManager.GetString("Messages_View_Details_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message details.
        /// </summary>
        internal static string Messages_View_Details_MessageDetails {
            get {
                return ResourceManager.GetString("Messages_View_Details_MessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageType:.
        /// </summary>
        internal static string Messages_View_Details_MessageType {
            get {
                return ResourceManager.GetString("Messages_View_Details_MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusId:.
        /// </summary>
        internal static string Messages_View_Details_StatusId {
            get {
                return ResourceManager.GetString("Messages_View_Details_StatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        internal static string Messages_View_Details_Text {
            get {
                return ResourceManager.GetString("Messages_View_Details_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Messages_View_Details_Title {
            get {
                return ResourceManager.GetString("Messages_View_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string Messages_View_Details_To {
            get {
                return ResourceManager.GetString("Messages_View_Details_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Message Type.
        /// </summary>
        internal static string Messages_View_Index_CreateMessageType {
            get {
                return ResourceManager.GetString("Messages_View_Index_CreateMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Messages_View_Index_CreateNew {
            get {
                return ResourceManager.GetString("Messages_View_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Messages_View_Index_Date {
            get {
                return ResourceManager.GetString("Messages_View_Index_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Messages_View_Index_Delete {
            get {
                return ResourceManager.GetString("Messages_View_Index_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Messages_View_Index_Details {
            get {
                return ResourceManager.GetString("Messages_View_Index_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Messages_View_Index_Text {
            get {
                return ResourceManager.GetString("Messages_View_Index_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Messages_View_Index_Title {
            get {
                return ResourceManager.GetString("Messages_View_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Messages_View_MessageType_Create_BackToList {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Messages_View_MessageType_Create_Create {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Message Type.
        /// </summary>
        internal static string Messages_View_MessageType_Create_CreateMessageType {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Create_CreateMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Messages_View_MessageType_Create_Name {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Messages_View_MessageType_Edit_BackToList {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Edit_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Message Type.
        /// </summary>
        internal static string Messages_View_MessageType_Edit_EditMessageType {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Edit_EditMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Messages_View_MessageType_Edit_Name {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Messages_View_MessageType_Edit_Save {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Messages_View_MessageType_Index_CreateNew {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Messages_View_MessageType_Index_Edit {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Index_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Messages_View_MessageType_Index_Name {
            get {
                return ResourceManager.GetString("Messages_View_MessageType_Index_Name", resourceCulture);
            }
        }
    }
}
