//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PPP_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PPP_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PPP_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string PPP_View_ActiveConnections_Index_Address {
            get {
                return ResourceManager.GetString("PPP_View_ActiveConnections_Index_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallerId.
        /// </summary>
        internal static string PPP_View_ActiveConnections_Index_CallerId {
            get {
                return ResourceManager.GetString("PPP_View_ActiveConnections_Index_CallerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string PPP_View_ActiveConnections_Index_Encoding {
            get {
                return ResourceManager.GetString("PPP_View_ActiveConnections_Index_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimitBytesIn.
        /// </summary>
        internal static string PPP_View_ActiveConnections_Index_LimitBytesIn {
            get {
                return ResourceManager.GetString("PPP_View_ActiveConnections_Index_LimitBytesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimitBytesOut.
        /// </summary>
        internal static string PPP_View_ActiveConnections_Index_LimitBytesOut {
            get {
                return ResourceManager.GetString("PPP_View_ActiveConnections_Index_LimitBytesOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PPP_View_ActiveConnections_Index_Name {
            get {
                return ResourceManager.GetString("PPP_View_ActiveConnections_Index_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string PPP_View_ActiveConnections_Index_Service {
            get {
                return ResourceManager.GetString("PPP_View_ActiveConnections_Index_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId.
        /// </summary>
        internal static string PPP_View_ActiveConnections_Index_SessionId {
            get {
                return ResourceManager.GetString("PPP_View_ActiveConnections_Index_SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime.
        /// </summary>
        internal static string PPP_View_ActiveConnections_Index_Uptime {
            get {
                return ResourceManager.GetString("PPP_View_ActiveConnections_Index_Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses:.
        /// </summary>
        internal static string PPP_View_Pool_Create_Addresses {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Create_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string PPP_View_Pool_Create_BackToList {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string PPP_View_Pool_Create_Create {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Pool.
        /// </summary>
        internal static string PPP_View_Pool_Create_CreateNewPool {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Create_CreateNewPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string PPP_View_Pool_Create_Name {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextPool:.
        /// </summary>
        internal static string PPP_View_Pool_Create_NextPool {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Create_NextPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string PPP_View_Pool_Create_ValidationSummary {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Create_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses:.
        /// </summary>
        internal static string PPP_View_Pool_Edit_Addresses {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Edit_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string PPP_View_Pool_Edit_BackToList {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Edit_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Pool:.
        /// </summary>
        internal static string PPP_View_Pool_Edit_EditPool {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Edit_EditPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PPP_View_Pool_Edit_Name {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextPool:.
        /// </summary>
        internal static string PPP_View_Pool_Edit_NextPool {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Edit_NextPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string PPP_View_Pool_Edit_Save {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string PPP_View_Pool_Edit_ValidationSummary {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Edit_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string PPP_View_Pool_Index_Addresses {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Index_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string PPP_View_Pool_Index_CreateNew {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string PPP_View_Pool_Index_Delete {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Index_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string PPP_View_Pool_Index_DeleteAll {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Index_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PPP_View_Pool_Index_Name {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Index_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextPool.
        /// </summary>
        internal static string PPP_View_Pool_Index_NextPool {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Index_NextPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was unsuccessful. Please view details and try again..
        /// </summary>
        internal static string PPP_View_Pool_Index_ValidationSummary {
            get {
                return ResourceManager.GetString("PPP_View_Pool_Index_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string PPP_View_Profile_Create_BackToList {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string PPP_View_Profile_Create_Comment {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string PPP_View_Profile_Create_Cost {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string PPP_View_Profile_Create_Create {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Profile.
        /// </summary>
        internal static string PPP_View_Profile_Create_CreateNewProfile {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_CreateNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        internal static string PPP_View_Profile_Create_DisplayName {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalAddress.
        /// </summary>
        internal static string PPP_View_Profile_Create_LocalAddress {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_LocalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PPP_View_Profile_Create_Name {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        internal static string PPP_View_Profile_Create_Pool {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateLimit.
        /// </summary>
        internal static string PPP_View_Profile_Create_RateLimit {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_RateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string PPP_View_Profile_Create_ValidationSummary {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Create_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string PPP_View_Profile_Edit_BackToList {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string PPP_View_Profile_Edit_Comment {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string PPP_View_Profile_Edit_Cost {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string PPP_View_Profile_Edit_DisplayName {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string PPP_View_Profile_Edit_EditProfile {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalAddress.
        /// </summary>
        internal static string PPP_View_Profile_Edit_LocalAddress {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_LocalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PPP_View_Profile_Edit_Name {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        internal static string PPP_View_Profile_Edit_Pool {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateLimit.
        /// </summary>
        internal static string PPP_View_Profile_Edit_RateLimit {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_RateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string PPP_View_Profile_Edit_Save {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string PPP_View_Profile_Edit_ValidationSummary {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Edit_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string PPP_View_Profile_Index_Cost {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Index_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string PPP_View_Profile_Index_CreateNew {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string PPP_View_Profile_Index_Delete {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Index_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profiles.
        /// </summary>
        internal static string PPP_View_Profile_Index_DeleteProfiles {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Index_DeleteProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalAddress.
        /// </summary>
        internal static string PPP_View_Profile_Index_LocalAddress {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Index_LocalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PPP_View_Profile_Index_Name {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Index_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        internal static string PPP_View_Profile_Index_Pool {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Index_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateLimit.
        /// </summary>
        internal static string PPP_View_Profile_Index_RateLimit {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Index_RateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was unsuccessful. Please view details and try again..
        /// </summary>
        internal static string PPP_View_Profile_Index_ValidationSummary {
            get {
                return ResourceManager.GetString("PPP_View_Profile_Index_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallerId.
        /// </summary>
        internal static string PPP_View_Secret_Edit_CallerId {
            get {
                return ResourceManager.GetString("PPP_View_Secret_Edit_CallerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimitBytesIn.
        /// </summary>
        internal static string PPP_View_Secret_Edit_LimitBytesIn {
            get {
                return ResourceManager.GetString("PPP_View_Secret_Edit_LimitBytesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimitBytesOut.
        /// </summary>
        internal static string PPP_View_Secret_Edit_LimitBytesOut {
            get {
                return ResourceManager.GetString("PPP_View_Secret_Edit_LimitBytesOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalAddress.
        /// </summary>
        internal static string PPP_View_Secret_Edit_LocalAddress {
            get {
                return ResourceManager.GetString("PPP_View_Secret_Edit_LocalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoteAddress.
        /// </summary>
        internal static string PPP_View_Secret_Edit_RemoteAddress {
            get {
                return ResourceManager.GetString("PPP_View_Secret_Edit_RemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        internal static string PPP_View_Secret_Edit_Routes {
            get {
                return ResourceManager.GetString("PPP_View_Secret_Edit_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string PPP_View_Secret_Edit_Service {
            get {
                return ResourceManager.GetString("PPP_View_Secret_Edit_Service", resourceCulture);
            }
        }
    }
}
