//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Services_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Services_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Services_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Services_View_ClientServices_BackToList {
            get {
                return ResourceManager.GetString("Services_View_ClientServices_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Services_View_ClientServices_Save {
            get {
                return ResourceManager.GetString("Services_View_ClientServices_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services_View_ClientServices_Services {
            get {
                return ResourceManager.GetString("Services_View_ClientServices_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Services_View_Create_Active {
            get {
                return ResourceManager.GetString("Services_View_Create_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Services_View_Create_BackToList {
            get {
                return ResourceManager.GetString("Services_View_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Services_View_Create_Comment {
            get {
                return ResourceManager.GetString("Services_View_Create_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Services_View_Create_Cost {
            get {
                return ResourceManager.GetString("Services_View_Create_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Services_View_Create_Create {
            get {
                return ResourceManager.GetString("Services_View_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Service.
        /// </summary>
        internal static string Services_View_Create_CreateNewService {
            get {
                return ResourceManager.GetString("Services_View_Create_CreateNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsRegular.
        /// </summary>
        internal static string Services_View_Create_IsRegular {
            get {
                return ResourceManager.GetString("Services_View_Create_IsRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Services_View_Create_Name {
            get {
                return ResourceManager.GetString("Services_View_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string Services_View_Create_ValidationSummary {
            get {
                return ResourceManager.GetString("Services_View_Create_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string Services_View_Create_Visible {
            get {
                return ResourceManager.GetString("Services_View_Create_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service.
        /// </summary>
        internal static string Services_View_Edit_EditService {
            get {
                return ResourceManager.GetString("Services_View_Edit_EditService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Services_View_Edit_Save {
            get {
                return ResourceManager.GetString("Services_View_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string Services_View_Edit_ValidationSummary {
            get {
                return ResourceManager.GetString("Services_View_Edit_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Services_View_Index_BackToList {
            get {
                return ResourceManager.GetString("Services_View_Index_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Services_View_Index_Client {
            get {
                return ResourceManager.GetString("Services_View_Index_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Services_View_Index_Cost {
            get {
                return ResourceManager.GetString("Services_View_Index_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Services_View_Index_CreateNew {
            get {
                return ResourceManager.GetString("Services_View_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User.
        /// </summary>
        internal static string Services_View_Index_ModifyUser {
            get {
                return ResourceManager.GetString("Services_View_Index_ModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Services_View_Index_Service {
            get {
                return ResourceManager.GetString("Services_View_Index_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Activity.
        /// </summary>
        internal static string Services_View_Index_ServiceActivity {
            get {
                return ResourceManager.GetString("Services_View_Index_ServiceActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        internal static string Services_View_Index_StartDate {
            get {
                return ResourceManager.GetString("Services_View_Index_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Services_View_Index_Status {
            get {
                return ResourceManager.GetString("Services_View_Index_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Services_View_Index_Type {
            get {
                return ResourceManager.GetString("Services_View_Index_Type", resourceCulture);
            }
        }
    }
}
