//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Users_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Users_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Users_User_Edit_BackToList {
            get {
                return ResourceManager.GetString("Users_User_Edit_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Users_User_Edit_Balance {
            get {
                return ResourceManager.GetString("Users_User_Edit_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Users_User_Edit_Comment {
            get {
                return ResourceManager.GetString("Users_User_Edit_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Users_User_Edit_Credit {
            get {
                return ResourceManager.GetString("Users_User_Edit_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User:.
        /// </summary>
        internal static string Users_User_Edit_EditUser {
            get {
                return ResourceManager.GetString("Users_User_Edit_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Users_User_Edit_Email {
            get {
                return ResourceManager.GetString("Users_User_Edit_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Users_User_Edit_General {
            get {
                return ResourceManager.GetString("Users_User_Edit_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Users_User_Edit_Password {
            get {
                return ResourceManager.GetString("Users_User_Edit_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Users_User_Edit_Profile {
            get {
                return ResourceManager.GetString("Users_User_Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Users_User_Edit_Role {
            get {
                return ResourceManager.GetString("Users_User_Edit_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Users_User_Edit_Save {
            get {
                return ResourceManager.GetString("Users_User_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Users_User_Edit_Status {
            get {
                return ResourceManager.GetString("Users_User_Edit_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string Users_User_Edit_UserName {
            get {
                return ResourceManager.GetString("Users_User_Edit_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string Users_User_Edit_ValidationSummary {
            get {
                return ResourceManager.GetString("Users_User_Edit_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string Users_User_Index_Addresses {
            get {
                return ResourceManager.GetString("Users_User_Index_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Users_User_Index_Balance {
            get {
                return ResourceManager.GetString("Users_User_Index_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Users_User_Index_CreateNew {
            get {
                return ResourceManager.GetString("Users_User_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Users.
        /// </summary>
        internal static string Users_User_Index_DeleteAllUsers {
            get {
                return ResourceManager.GetString("Users_User_Index_DeleteAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        internal static string Users_User_Index_FullName {
            get {
                return ResourceManager.GetString("Users_User_Index_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Users_User_Index_Load {
            get {
                return ResourceManager.GetString("Users_User_Index_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileName.
        /// </summary>
        internal static string Users_User_Index_ProfileName {
            get {
                return ResourceManager.GetString("Users_User_Index_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Users_User_Index_Role {
            get {
                return ResourceManager.GetString("Users_User_Index_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Users_User_Index_Services {
            get {
                return ResourceManager.GetString("Users_User_Index_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Users_User_Index_Status {
            get {
                return ResourceManager.GetString("Users_User_Index_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses.
        /// </summary>
        internal static string Users_User_Index_Statuses {
            get {
                return ResourceManager.GetString("Users_User_Index_Statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string Users_User_Index_UserName {
            get {
                return ResourceManager.GetString("Users_User_Index_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was unsuccessful. Please view details and try again..
        /// </summary>
        internal static string Users_User_Index_ValidationSummary {
            get {
                return ResourceManager.GetString("Users_User_Index_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Users_User_Index_View {
            get {
                return ResourceManager.GetString("Users_User_Index_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Users_User_Load_BackToList {
            get {
                return ResourceManager.GetString("Users_User_Load_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Users_User_Load_Balance {
            get {
                return ResourceManager.GetString("Users_User_Load_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Users_User_Load_Comment {
            get {
                return ResourceManager.GetString("Users_User_Load_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Modey for:.
        /// </summary>
        internal static string Users_User_Load_LoadMoneyFor {
            get {
                return ResourceManager.GetString("Users_User_Load_LoadMoneyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Users_User_Load_Method {
            get {
                return ResourceManager.GetString("Users_User_Load_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Users_User_Load_Save {
            get {
                return ResourceManager.GetString("Users_User_Load_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string Users_User_Load_Sum {
            get {
                return ResourceManager.GetString("Users_User_Load_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was unsuccessful. Please view details and try again..
        /// </summary>
        internal static string Users_User_Load_ValidationSummary {
            get {
                return ResourceManager.GetString("Users_User_Load_ValidationSummary", resourceCulture);
            }
        }
    }
}
