//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Users_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Users_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        internal static string Users_Detail_Edit_FirstName {
            get {
                return ResourceManager.GetString("Users_Detail_Edit_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        internal static string Users_Detail_Edit_LastName {
            get {
                return ResourceManager.GetString("Users_Detail_Edit_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name:.
        /// </summary>
        internal static string Users_Detail_Edit_MiddleName {
            get {
                return ResourceManager.GetString("Users_Detail_Edit_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Users_Shared_AddressUserControl_Address {
            get {
                return ResourceManager.GetString("Users_Shared_AddressUserControl_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Users_Shared_ContractUserControl_Comment {
            get {
                return ResourceManager.GetString("Users_Shared_ContractUserControl_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string Users_Shared_ContractUserControl_Contract {
            get {
                return ResourceManager.GetString("Users_Shared_ContractUserControl_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractNumber.
        /// </summary>
        internal static string Users_Shared_ContractUserControl_ContractNumber {
            get {
                return ResourceManager.GetString("Users_Shared_ContractUserControl_ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        internal static string Users_Shared_ContractUserControl_CreateDate {
            get {
                return ResourceManager.GetString("Users_Shared_ContractUserControl_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiredDate.
        /// </summary>
        internal static string Users_Shared_ContractUserControl_ExpiredDate {
            get {
                return ResourceManager.GetString("Users_Shared_ContractUserControl_ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        internal static string Users_Shared_DetailsUserControl_Balance {
            get {
                return ResourceManager.GetString("Users_Shared_DetailsUserControl_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string Users_Shared_DetailsUserControl_Comment {
            get {
                return ResourceManager.GetString("Users_Shared_DetailsUserControl_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Users_Shared_DetailsUserControl_Details {
            get {
                return ResourceManager.GetString("Users_Shared_DetailsUserControl_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Users_Shared_DetailsUserControl_Email {
            get {
                return ResourceManager.GetString("Users_Shared_DetailsUserControl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        internal static string Users_Shared_DetailsUserControl_FullName {
            get {
                return ResourceManager.GetString("Users_Shared_DetailsUserControl_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport:.
        /// </summary>
        internal static string Users_Shared_DetailsUserControl_Passport {
            get {
                return ResourceManager.GetString("Users_Shared_DetailsUserControl_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Comment:.
        /// </summary>
        internal static string Users_Shared_DetailsUserControl_PassportComment {
            get {
                return ResourceManager.GetString("Users_Shared_DetailsUserControl_PassportComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Delivery Date:.
        /// </summary>
        internal static string Users_Shared_DetailsUserControl_PassportDeliveryDate {
            get {
                return ResourceManager.GetString("Users_Shared_DetailsUserControl_PassportDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Users_Shared_DetailsUserControl_Status {
            get {
                return ResourceManager.GetString("Users_Shared_DetailsUserControl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_Comment {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHCP Address:.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_DHCPAddress {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_DHCPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_Disabled {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Address:.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_LocalAddress {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_LocalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address:.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_MACAddress {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_MACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_Name {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_Password {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPP Secret.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_PPPSecret {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_PPPSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_Profile {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Address:.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_RemoteAddress {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_RemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes:.
        /// </summary>
        internal static string Users_Shared_PPPSecretUserControl_Routes {
            get {
                return ResourceManager.GetString("Users_Shared_PPPSecretUserControl_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Users_Shared_ServicesUserControl_Name {
            get {
                return ResourceManager.GetString("Users_Shared_ServicesUserControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Users_Shared_ServicesUserControl_Services {
            get {
                return ResourceManager.GetString("Users_Shared_ServicesUserControl_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Users_User_Create_BackToList {
            get {
                return ResourceManager.GetString("Users_User_Create_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Users_User_Create_Create {
            get {
                return ResourceManager.GetString("Users_User_Create_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        internal static string Users_User_Create_CreateNewUser {
            get {
                return ResourceManager.GetString("Users_User_Create_CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Users_User_Create_Credit {
            get {
                return ResourceManager.GetString("Users_User_Create_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Users_User_Create_Email {
            get {
                return ResourceManager.GetString("Users_User_Create_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Users_User_Create_Generate {
            get {
                return ResourceManager.GetString("Users_User_Create_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Users_User_Create_Password {
            get {
                return ResourceManager.GetString("Users_User_Create_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Users_User_Create_Profile {
            get {
                return ResourceManager.GetString("Users_User_Create_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Users_User_Create_Role {
            get {
                return ResourceManager.GetString("Users_User_Create_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Users_User_Create_Status {
            get {
                return ResourceManager.GetString("Users_User_Create_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string Users_User_Create_UserName {
            get {
                return ResourceManager.GetString("Users_User_Create_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string Users_User_Create_ValidationSummary {
            get {
                return ResourceManager.GetString("Users_User_Create_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Users_User_Edit_Add {
            get {
                return ResourceManager.GetString("Users_User_Edit_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Users_User_Edit_BackToList {
            get {
                return ResourceManager.GetString("Users_User_Edit_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Users_User_Edit_Balance {
            get {
                return ResourceManager.GetString("Users_User_Edit_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Users_User_Edit_Comment {
            get {
                return ResourceManager.GetString("Users_User_Edit_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Users_User_Edit_Credit {
            get {
                return ResourceManager.GetString("Users_User_Edit_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Users_User_Edit_Edit {
            get {
                return ResourceManager.GetString("Users_User_Edit_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User:.
        /// </summary>
        internal static string Users_User_Edit_EditUser {
            get {
                return ResourceManager.GetString("Users_User_Edit_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Users_User_Edit_Email {
            get {
                return ResourceManager.GetString("Users_User_Edit_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Users_User_Edit_General {
            get {
                return ResourceManager.GetString("Users_User_Edit_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Users_User_Edit_Password {
            get {
                return ResourceManager.GetString("Users_User_Edit_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Users_User_Edit_Profile {
            get {
                return ResourceManager.GetString("Users_User_Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Users_User_Edit_Role {
            get {
                return ResourceManager.GetString("Users_User_Edit_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Users_User_Edit_Save {
            get {
                return ResourceManager.GetString("Users_User_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Users_User_Edit_Status {
            get {
                return ResourceManager.GetString("Users_User_Edit_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string Users_User_Edit_UserName {
            get {
                return ResourceManager.GetString("Users_User_Edit_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string Users_User_Edit_ValidationSummary {
            get {
                return ResourceManager.GetString("Users_User_Edit_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Users_User_Index_Balance {
            get {
                return ResourceManager.GetString("Users_User_Index_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Users_User_Index_CreateNew {
            get {
                return ResourceManager.GetString("Users_User_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Users.
        /// </summary>
        internal static string Users_User_Index_DeleteAllUsers {
            get {
                return ResourceManager.GetString("Users_User_Index_DeleteAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        internal static string Users_User_Index_FullName {
            get {
                return ResourceManager.GetString("Users_User_Index_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Users_User_Index_Load {
            get {
                return ResourceManager.GetString("Users_User_Index_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileName.
        /// </summary>
        internal static string Users_User_Index_ProfileName {
            get {
                return ResourceManager.GetString("Users_User_Index_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Users_User_Index_Role {
            get {
                return ResourceManager.GetString("Users_User_Index_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Users_User_Index_Services {
            get {
                return ResourceManager.GetString("Users_User_Index_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Users_User_Index_Status {
            get {
                return ResourceManager.GetString("Users_User_Index_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses.
        /// </summary>
        internal static string Users_User_Index_Statuses {
            get {
                return ResourceManager.GetString("Users_User_Index_Statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string Users_User_Index_UserName {
            get {
                return ResourceManager.GetString("Users_User_Index_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was unsuccessful. Please view details and try again..
        /// </summary>
        internal static string Users_User_Index_ValidationSummary {
            get {
                return ResourceManager.GetString("Users_User_Index_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Users_User_Index_View {
            get {
                return ResourceManager.GetString("Users_User_Index_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Users_User_Load_BackToList {
            get {
                return ResourceManager.GetString("Users_User_Load_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Users_User_Load_Balance {
            get {
                return ResourceManager.GetString("Users_User_Load_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Users_User_Load_Comment {
            get {
                return ResourceManager.GetString("Users_User_Load_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Modey for:.
        /// </summary>
        internal static string Users_User_Load_LoadMoneyFor {
            get {
                return ResourceManager.GetString("Users_User_Load_LoadMoneyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Users_User_Load_Method {
            get {
                return ResourceManager.GetString("Users_User_Load_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Users_User_Load_Save {
            get {
                return ResourceManager.GetString("Users_User_Load_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string Users_User_Load_Sum {
            get {
                return ResourceManager.GetString("Users_User_Load_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was unsuccessful. Please view details and try again..
        /// </summary>
        internal static string Users_User_Load_ValidationSummary {
            get {
                return ResourceManager.GetString("Users_User_Load_ValidationSummary", resourceCulture);
            }
        }
    }
}
