//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.User_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        internal static string Site_View_Account_ChangePasswordSuccess_P1 {
            get {
                return ResourceManager.GetString("Site_View_Account_ChangePasswordSuccess_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string Site_View_Account_ChangePassword_AccountInformation {
            get {
                return ResourceManager.GetString("Site_View_Account_ChangePassword_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Site_View_Account_ChangePassword_Button {
            get {
                return ResourceManager.GetString("Site_View_Account_ChangePassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password:.
        /// </summary>
        internal static string Site_View_Account_ChangePassword_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Site_View_Account_ChangePassword_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password:.
        /// </summary>
        internal static string Site_View_Account_ChangePassword_CurrentPassword {
            get {
                return ResourceManager.GetString("Site_View_Account_ChangePassword_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        internal static string Site_View_Account_ChangePassword_NewPassword {
            get {
                return ResourceManager.GetString("Site_View_Account_ChangePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to change your password..
        /// </summary>
        internal static string Site_View_Account_ChangePassword_P1 {
            get {
                return ResourceManager.GetString("Site_View_Account_ChangePassword_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords are required to be a minimum of &lt;%=Html.Encode(ViewData[&quot;PasswordLength&quot;])%&gt; characters in length..
        /// </summary>
        internal static string Site_View_Account_ChangePassword_P2 {
            get {
                return ResourceManager.GetString("Site_View_Account_ChangePassword_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Site_View_Account_ChangePassword_Title {
            get {
                return ResourceManager.GetString("Site_View_Account_ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        internal static string Site_View_Account_Index_Balance {
            get {
                return ResourceManager.GetString("Site_View_Account_Index_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Site_View_Account_Index_Email {
            get {
                return ResourceManager.GetString("Site_View_Account_Index_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName:.
        /// </summary>
        internal static string Site_View_Account_Index_FullName {
            get {
                return ResourceManager.GetString("Site_View_Account_Index_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TariffName:.
        /// </summary>
        internal static string Site_View_Account_Index_TariffName {
            get {
                return ResourceManager.GetString("Site_View_Account_Index_TariffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data.
        /// </summary>
        internal static string Site_View_Account_Index_UserData {
            get {
                return ResourceManager.GetString("Site_View_Account_Index_UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        internal static string Site_View_Account_Index_UserName {
            get {
                return ResourceManager.GetString("Site_View_Account_Index_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string Site_View_Account_LogOn_AccountInformation {
            get {
                return ResourceManager.GetString("Site_View_Account_LogOn_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        internal static string Site_View_Account_LogOn_Button_LogOn {
            get {
                return ResourceManager.GetString("Site_View_Account_LogOn_Button_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Site_View_Account_LogOn_Password {
            get {
                return ResourceManager.GetString("Site_View_Account_LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string Site_View_Account_LogOn_RememberMe {
            get {
                return ResourceManager.GetString("Site_View_Account_LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        internal static string Site_View_Account_LogOn_Title {
            get {
                return ResourceManager.GetString("Site_View_Account_LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Site_View_Account_LogOn_Username {
            get {
                return ResourceManager.GetString("Site_View_Account_LogOn_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string Site_View_Account_Register_AccountInformation {
            get {
                return ResourceManager.GetString("Site_View_Account_Register_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        internal static string Site_View_Account_Register_AccountInformation_ConfirmPassword {
            get {
                return ResourceManager.GetString("Site_View_Account_Register_AccountInformation_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Site_View_Account_Register_AccountInformation_Email {
            get {
                return ResourceManager.GetString("Site_View_Account_Register_AccountInformation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Site_View_Account_Register_AccountInformation_Password {
            get {
                return ResourceManager.GetString("Site_View_Account_Register_AccountInformation_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Site_View_Account_Register_AccountInformation_Register {
            get {
                return ResourceManager.GetString("Site_View_Account_Register_AccountInformation_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Site_View_Account_Register_AccountInformation_Username {
            get {
                return ResourceManager.GetString("Site_View_Account_Register_AccountInformation_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new account..
        /// </summary>
        internal static string Site_View_Account_Register_P1 {
            get {
                return ResourceManager.GetString("Site_View_Account_Register_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of &lt;%=Html.Encode(ViewData[&quot;PasswordLength&quot;])%&gt; characters in length..
        /// </summary>
        internal static string Site_View_Account_Register_P2 {
            get {
                return ResourceManager.GetString("Site_View_Account_Register_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Site_View_Account_Register_Title {
            get {
                return ResourceManager.GetString("Site_View_Account_Register_Title", resourceCulture);
            }
        }
    }
}
